spring.config.active.on-profile: dev

spring:
  datasource:
    url: jdbc:h2:mem:book;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true


---
spring.config.active.on-profile: prod

storage:
  booking:
    path: ${BOOKING_STORAGE_PATH:./data/bookings.json}