spring:
  application:
    name: book-n-stay
  config:
    import: optional:classpath:/custom/
  profiles:
    include: db, security
    active: dev
  threads:
    virtual:
      enabled: true

server:
  port: 8080
  shutdown: graceful

---
spring.config.active.on-profile: dev
app:
  phase: DEV

logging:
  level:
    root: INFO
    org.keon.book: DEBUG

---
spring.config.active.on-profile: prod
app:
  phase: PROD

booking:
  storage:
    path: ${BOOKING_STORAGE_PATH:./data/bookings.json}

logging:
  level:
    root: WARN
    org.keon.book: INFO
