spring:
  application:
    name: book-n-stay
  config:
    import: optional:classpath:/custom/
  profiles:
    include: db, security
    active: dev
  threads:
    virtual:
      enabled: true
  cache:
    type: caffeine

cache:
  kakao-user:
    ttl: PT10M
    maximum-size: 1000

server:
  port: 8080
  shutdown: graceful

---
spring.config.active.on-profile: dev
app:
  phase: DEV

logging:
  level:
    root: INFO
    org.keon.book: DEBUG

---
spring.config.active.on-profile: prod
app:
  phase: PROD

logging:
  level:
    root: WARN
    org.keon.book: INFO
