apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-n-stay
  namespace: book-n-stay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-n-stay
  template:
    metadata:
      labels:
        app: book-n-stay
    spec:
      containers:
        - name: app
          image: book-n-stay:prod
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - name: app-data
              mountPath: /var/book-n-stay/data
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: book-n-stay-pvc
