apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: book-n-stay-ing
  namespace: book-n-stay
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - book-n-stay.example.com
      secretName: book-n-stay-tls
  rules:
    - host: book-n-stay.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: book-n-stay-svc
                port:
                  number: 80
