apiVersion: v1
kind: Service
metadata:
  name: book-n-stay-svc
  namespace: book-n-stay
spec:
  selector:
    app: book-n-stay
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP