apiVersion: v1
kind: PersistentVolume
metadata:
  name: book-n-stay-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: book-n-stay-retain
  hostPath:
    path: /mnt/data/book-n-stay
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: book-n-stay-pvc
  namespace: book-n-stay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: book-n-stay-retain
